// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserActionType int32

const (
	UserActionType_Connect UserActionType = 0
	UserActionType_Message UserActionType = 2
)

var UserActionType_name = map[int32]string{
	0: "Connect",
	2: "Message",
}

var UserActionType_value = map[string]int32{
	"Connect": 0,
	"Message": 2,
}

func (x UserActionType) String() string {
	return proto.EnumName(UserActionType_name, int32(x))
}

func (UserActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterRoomRequest struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRoomRequest) Reset()         { *m = RegisterRoomRequest{} }
func (m *RegisterRoomRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRoomRequest) ProtoMessage()    {}
func (*RegisterRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *RegisterRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRoomRequest.Unmarshal(m, b)
}
func (m *RegisterRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRoomRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRoomRequest.Merge(m, src)
}
func (m *RegisterRoomRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRoomRequest.Size(m)
}
func (m *RegisterRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRoomRequest proto.InternalMessageInfo

func (m *RegisterRoomRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type EnterRoomRequest struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRoomRequest) Reset()         { *m = EnterRoomRequest{} }
func (m *EnterRoomRequest) String() string { return proto.CompactTextString(m) }
func (*EnterRoomRequest) ProtoMessage()    {}
func (*EnterRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *EnterRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomRequest.Unmarshal(m, b)
}
func (m *EnterRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomRequest.Marshal(b, m, deterministic)
}
func (m *EnterRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomRequest.Merge(m, src)
}
func (m *EnterRoomRequest) XXX_Size() int {
	return xxx_messageInfo_EnterRoomRequest.Size(m)
}
func (m *EnterRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomRequest proto.InternalMessageInfo

func (m *EnterRoomRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *EnterRoomRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserMessage struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessage) Reset()         { *m = UserMessage{} }
func (m *UserMessage) String() string { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()    {}
func (*UserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *UserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessage.Unmarshal(m, b)
}
func (m *UserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessage.Marshal(b, m, deterministic)
}
func (m *UserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessage.Merge(m, src)
}
func (m *UserMessage) XXX_Size() int {
	return xxx_messageInfo_UserMessage.Size(m)
}
func (m *UserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessage proto.InternalMessageInfo

func (m *UserMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ServerChatAction struct {
	// Types that are valid to be assigned to Action:
	//	*ServerChatAction_Message
	//	*ServerChatAction_Stop
	Action               isServerChatAction_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ServerChatAction) Reset()         { *m = ServerChatAction{} }
func (m *ServerChatAction) String() string { return proto.CompactTextString(m) }
func (*ServerChatAction) ProtoMessage()    {}
func (*ServerChatAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *ServerChatAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerChatAction.Unmarshal(m, b)
}
func (m *ServerChatAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerChatAction.Marshal(b, m, deterministic)
}
func (m *ServerChatAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerChatAction.Merge(m, src)
}
func (m *ServerChatAction) XXX_Size() int {
	return xxx_messageInfo_ServerChatAction.Size(m)
}
func (m *ServerChatAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerChatAction.DiscardUnknown(m)
}

var xxx_messageInfo_ServerChatAction proto.InternalMessageInfo

type isServerChatAction_Action interface {
	isServerChatAction_Action()
}

type ServerChatAction_Message struct {
	Message *UserMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ServerChatAction_Stop struct {
	Stop *Empty `protobuf:"bytes,2,opt,name=stop,proto3,oneof"`
}

func (*ServerChatAction_Message) isServerChatAction_Action() {}

func (*ServerChatAction_Stop) isServerChatAction_Action() {}

func (m *ServerChatAction) GetAction() isServerChatAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ServerChatAction) GetMessage() *UserMessage {
	if x, ok := m.GetAction().(*ServerChatAction_Message); ok {
		return x.Message
	}
	return nil
}

func (m *ServerChatAction) GetStop() *Empty {
	if x, ok := m.GetAction().(*ServerChatAction_Stop); ok {
		return x.Stop
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerChatAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerChatAction_Message)(nil),
		(*ServerChatAction_Stop)(nil),
	}
}

type ConnectionInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionInfo) Reset()         { *m = ConnectionInfo{} }
func (m *ConnectionInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectionInfo) ProtoMessage()    {}
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *ConnectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionInfo.Unmarshal(m, b)
}
func (m *ConnectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionInfo.Marshal(b, m, deterministic)
}
func (m *ConnectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionInfo.Merge(m, src)
}
func (m *ConnectionInfo) XXX_Size() int {
	return xxx_messageInfo_ConnectionInfo.Size(m)
}
func (m *ConnectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionInfo proto.InternalMessageInfo

func (m *ConnectionInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ConnectionInfo) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type UserChatAction struct {
	// Types that are valid to be assigned to Action:
	//	*UserChatAction_Connect
	//	*UserChatAction_Message
	Action               isUserChatAction_Action `protobuf_oneof:"action"`
	Type                 UserActionType          `protobuf:"varint,4,opt,name=type,proto3,enum=chat.UserActionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UserChatAction) Reset()         { *m = UserChatAction{} }
func (m *UserChatAction) String() string { return proto.CompactTextString(m) }
func (*UserChatAction) ProtoMessage()    {}
func (*UserChatAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *UserChatAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserChatAction.Unmarshal(m, b)
}
func (m *UserChatAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserChatAction.Marshal(b, m, deterministic)
}
func (m *UserChatAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserChatAction.Merge(m, src)
}
func (m *UserChatAction) XXX_Size() int {
	return xxx_messageInfo_UserChatAction.Size(m)
}
func (m *UserChatAction) XXX_DiscardUnknown() {
	xxx_messageInfo_UserChatAction.DiscardUnknown(m)
}

var xxx_messageInfo_UserChatAction proto.InternalMessageInfo

type isUserChatAction_Action interface {
	isUserChatAction_Action()
}

type UserChatAction_Connect struct {
	Connect *ConnectionInfo `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type UserChatAction_Message struct {
	Message *UserMessage `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

func (*UserChatAction_Connect) isUserChatAction_Action() {}

func (*UserChatAction_Message) isUserChatAction_Action() {}

func (m *UserChatAction) GetAction() isUserChatAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *UserChatAction) GetConnect() *ConnectionInfo {
	if x, ok := m.GetAction().(*UserChatAction_Connect); ok {
		return x.Connect
	}
	return nil
}

func (m *UserChatAction) GetMessage() *UserMessage {
	if x, ok := m.GetAction().(*UserChatAction_Message); ok {
		return x.Message
	}
	return nil
}

func (m *UserChatAction) GetType() UserActionType {
	if m != nil {
		return m.Type
	}
	return UserActionType_Connect
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UserChatAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UserChatAction_Connect)(nil),
		(*UserChatAction_Message)(nil),
	}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("chat.UserActionType", UserActionType_name, UserActionType_value)
	proto.RegisterType((*User)(nil), "chat.User")
	proto.RegisterType((*RegisterRoomRequest)(nil), "chat.RegisterRoomRequest")
	proto.RegisterType((*EnterRoomRequest)(nil), "chat.EnterRoomRequest")
	proto.RegisterType((*UserMessage)(nil), "chat.UserMessage")
	proto.RegisterType((*ServerChatAction)(nil), "chat.ServerChatAction")
	proto.RegisterType((*ConnectionInfo)(nil), "chat.ConnectionInfo")
	proto.RegisterType((*UserChatAction)(nil), "chat.UserChatAction")
	proto.RegisterType((*Empty)(nil), "chat.Empty")
}

func init() {
	proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54)
}

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0xaf, 0x93, 0x40,
	0x14, 0x05, 0x1c, 0xe1, 0xbd, 0x4b, 0x82, 0x38, 0x9a, 0x17, 0x7c, 0x0b, 0x53, 0x59, 0x91, 0x26,
	0xad, 0x0d, 0x2e, 0x75, 0xa1, 0x6d, 0x1a, 0x5b, 0x13, 0x5d, 0x50, 0xdd, 0xb8, 0xc3, 0xf6, 0xda,
	0xb2, 0x60, 0x06, 0x87, 0xa9, 0xa6, 0x3f, 0xc8, 0x9f, 0xe0, 0xff, 0x33, 0xf3, 0x81, 0x50, 0x63,
	0x7c, 0xdd, 0xcd, 0x61, 0xce, 0x9c, 0x73, 0xee, 0xc9, 0x05, 0x60, 0x7b, 0x28, 0xe5, 0xb4, 0x11,
	0x5c, 0x72, 0x4a, 0xd4, 0x39, 0x1d, 0x03, 0xf9, 0xd4, 0xa2, 0xa0, 0x11, 0x78, 0xd5, 0x2e, 0x71,
	0x47, 0x6e, 0x76, 0x5d, 0x78, 0xd5, 0x8e, 0x52, 0x20, 0xac, 0xac, 0x31, 0xf1, 0xf4, 0x17, 0x7d,
	0x4e, 0x27, 0xf0, 0xa8, 0xc0, 0x7d, 0xd5, 0x4a, 0x14, 0x05, 0xe7, 0x75, 0x81, 0xdf, 0x8e, 0xd8,
	0x4a, 0x7a, 0x03, 0xbe, 0xe0, 0xbc, 0x5e, 0x77, 0xcf, 0x2d, 0x4a, 0xdf, 0x41, 0xbc, 0x64, 0x97,
	0x71, 0xe9, 0x53, 0x20, 0xc7, 0x16, 0x85, 0xb6, 0x0b, 0x73, 0x98, 0xea, 0x9c, 0x2a, 0x58, 0xa1,
	0xbf, 0xa7, 0x6f, 0x21, 0x54, 0xe8, 0x3d, 0xb6, 0x6d, 0xb9, 0x47, 0x9a, 0x40, 0x50, 0x9b, 0xa3,
	0xd5, 0xe9, 0xe0, 0x9d, 0x42, 0x0c, 0xe2, 0x0d, 0x8a, 0xef, 0x28, 0x16, 0x87, 0x52, 0xbe, 0xd9,
	0xca, 0x8a, 0x33, 0x3a, 0x39, 0x57, 0x0b, 0xf3, 0x87, 0xfd, 0x33, 0xeb, 0xb8, 0x72, 0x7a, 0x8b,
	0x67, 0x40, 0x5a, 0xc9, 0x1b, 0x6b, 0x11, 0x1a, 0xee, 0xb2, 0x6e, 0xe4, 0x69, 0xe5, 0x14, 0xfa,
	0x6a, 0x7e, 0x05, 0x7e, 0xa9, 0xb5, 0xd3, 0xd7, 0x10, 0x2d, 0x38, 0x63, 0xa8, 0xd1, 0x9a, 0x7d,
	0xe5, 0xaa, 0x02, 0x95, 0xa4, 0xaf, 0xc0, 0xa0, 0x41, 0x35, 0xde, 0x59, 0x8d, 0x3f, 0x5d, 0x88,
	0x54, 0x92, 0x41, 0xe0, 0x19, 0x04, 0x5b, 0x23, 0x6a, 0x03, 0x3f, 0x36, 0x21, 0xce, 0x9d, 0x54,
	0x66, 0x4b, 0x1b, 0x8e, 0x78, 0xef, 0x82, 0x11, 0x33, 0x20, 0xf2, 0xd4, 0x60, 0x42, 0x46, 0x6e,
	0x16, 0x75, 0xea, 0x8a, 0x6b, 0x02, 0x7c, 0x3c, 0x35, 0x58, 0x68, 0xc6, 0x60, 0xd2, 0x00, 0xee,
	0xeb, 0x12, 0xc6, 0x63, 0x93, 0xb7, 0xa7, 0xd2, 0x10, 0x02, 0x1b, 0x2d, 0x76, 0x14, 0xb0, 0x8e,
	0xb1, 0x97, 0xff, 0x72, 0x81, 0xa8, 0xc1, 0xe8, 0x4b, 0x78, 0xd0, 0xed, 0xd6, 0x07, 0xfc, 0xa1,
	0x56, 0x86, 0x3e, 0x31, 0xb6, 0xff, 0x58, 0xb9, 0xdb, 0x61, 0xe9, 0xa9, 0x43, 0x73, 0xb8, 0xfe,
	0xb3, 0x69, 0xf4, 0xc6, 0xde, 0xb1, 0xff, 0xbf, 0x79, 0x05, 0xfe, 0x46, 0x0a, 0x2c, 0x6b, 0x3a,
	0x18, 0xaf, 0xef, 0xf8, 0xd6, 0xca, 0xfc, 0xbd, 0x2c, 0xa9, 0x93, 0xb9, 0x33, 0x77, 0x7e, 0xf5,
	0xd9, 0x9f, 0x3e, 0x57, 0x84, 0x2f, 0xbe, 0xfe, 0x9b, 0x5e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x3c, 0xf8, 0x2d, 0xad, 0x5b, 0x03, 0x00, 0x00,
}
